final List Listmessages = [

  {
    "name": 'Brandy Prescott',
    "chat": 'Hi Mike, How are you?',
    "time": '3 min',
    "image": 'assets/images/Sukuna.jpg',
    "status": false,
    "isMe": true,
  },
  {
    "name": 'Brandy Prescott',
    "chat": 'Hi Mike, How are you?',
    "time": '3 min',
    "image": 'assets/images/Sukuna.jpg',
    "status": true,
    "isMe": false,
  },
  {
    "name": 'Brandy Prescott',
    "chat": 'Hi Mike, How are you?',
    "time": '3 min',
    "image": 'assets/images/Sukuna.jpg',
    "status": true,
    "isMe": true,
  },
  {
    "name": 'Lester Phillips',
    "chat": 'Hi Mike, How are you?',
    "time": '3 min',
    "image": 'assets/images/Sukuna  8K.png',
    "status": true,
    "isMe": false,
  },
  {
    "name": 'Deann Harvey',
    "chat": 'Hi Mike, How are you?',
    "time": '3 min',
    "image": 'assets/images/Symmetrical Ratios.jpg',
    "status": false,
    "isMe": true,
  },
  {
    "name": 'Alex Smith',
    "chat": 'Please let me know your problemsPlease let me know your problems, Please let me know your problemsV, Please let me know your problems, Please let me know your problems',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": true,
    "isMe": false,
  },
  {
    "name": 'Quiche Hollandaise',
    "chat": 'Thanks for contact me. I need your help...?',
    "time": '3 min',
    "image": 'assets/images/The Game Awards 2022 No Text.jpg',
    "status": false,
    "isMe": true,
  },
  {
    "name": 'Quiche HollandaiseMarvin White',
    "chat": 'Okay, I will help you. Please explain what\'s the issue.',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": true,
    "isMe": false,
  },
  {
    "name": 'Quiche HollandaiseMarvin White',
    "chat": 'Okay, I will help you. Please explain what\'s the issue.',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": true,
    "isMe": true,
  },
  {
    "name": 'Quiche HollandaiseMarvin White',
    "chat": 'Okay, I will help you. Please explain what\'s the issue.',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": true,
    "isMe": false,
  },
  {
    "name": 'Quiche HollandaiseMarvin White',
    "chat": 'Okay, I will help you. Please explain what\'s the issue.',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": true,
    "isMe": true,
  },
  {
    "name": 'Quiche HollandaiseMarvin White',
    "chat": 'Okay, I will help you. Please explain what\'s the issue.',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": false,
    "isMe": false,
  },
  {
    "name": 'Quiche HollandaiseMarvin White',
    "chat": 'Okay, I will help you. Please explain what\'s the issue.',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": true,
    "isMe": true,
  },
  {
    "name": 'Quiche HollandaiseMarvin White',
    "chat": 'Okay, I will help you. Please explain what\'s the issue.',
    "time": '3 min',
    "image": 'assets/images/Sorxez.png',
    "status": false,
    "isMe": false,
  },
];